---
- hosts: 172.31.55.95
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: I want to copy file from master to nodes
    copy:
       src: mystatic
       dest: /home/ubuntu/mystaticfile